#Saftey
alias rm='rm -i'
alias cp='cp -i'
alias ln='ln -i'

#Convenience redefinitions
alias lsl='ls -lh --color=auto'
alias lsla='ls -lah --color=auto'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ccd='cd ~/ && clear'
alias cdd='cd /home/eebs/Desktop/'
alias ccdd='cd /home/eebs/Desktop/ && clear'
alias p='pwd'
alias h=history
alias c=clear
alias reloada='source ~/.bash_aliases'
alias 'icommandyoutodie'='exit'
alias log='sudo nano /var/log/vsftpd.log'
alias ud='sudo perl /home/eebs/parsevsftpd.pl'
alias usage='df -h |grep /mnt/media |cut -c 41-43'
alias restart='sh /home/eebs/restartserver.sh'
alias apt='sudo apt-get install'
alias gs='git status'
alias gc='git commit'
alias gb='git branch'
alias ga='git add'
alias gaa='git add --all'
alias gh='git push'
alias gl='git pull'
alias gg='git log --stat="120,120" --color'
alias gw='git-wtf'
alias gp='git log --graph --oneline --all'
alias pd='/var/www/phpdoc/phpdoc -d /var/www/ip -t /var/www/docs -ti WeaveNet -dn interestportal -pp on'
alias temp='cat /proc/acpi/thermal_zone/THRM/temperature'
alias zf='/usr/local/ZendFrameworkCli/bin/zf.sh'
alias tree='tree --charset ISO8859-1'
alias gi='git checkout import'
alias gm='git checkout master'
alias gitp='sh /home/eebs/scripts/push.sh'
